### ISSUE TITLE
Instances

### ISSUE THREAD

**Issue by danwdart** [MichelBoucey/NanoID#2]
Would be great to get various instances via the `ByteString` instance by default, e.g. `ToJSON`, `FromJSON`, `Generic`, maybe `Data`...

I guess after parity with https://github.com/haskell-hvr/uuid?

Thanks!

**Comment by MichelBoucey** [comment]
It's OK : A.S.A.P. !

**Comment by MichelBoucey** [comment]
I just pushed `nanoid-3.1.0` to Hackage with some useful instances.

Feel free to ask much more changes.
